<?php
/**
 * @var \Bluz\View\View $this
 */
?>
<?php $uid = uniqid('form_'); ?>
<form id="<?=$uid?>" action="<?=$this->url('contact-us', 'crud')?>" class="form-horizontal ajax" method="<?=$method?>">
    <input type="hidden" name="id" value="<?=$row->id?>"/>
    <input type="hidden" name="_method" value="<?=$method?>"/>
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title"><?=__('Edit page')?></h4>
        </div>
        <div class="modal-body">
            <div class="form-group">
                <label class="control-label col-lg-2" for="name"><?=__('Name')?>:</label>
                <div class="col-lg-10">
                    <input type="text" class="form-control" id="name" name="name" value="<?=$row->name?>" required />
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-lg-2" for="email"><?=__('Email')?>:</label>
                <div class="col-lg-10">
                    <input type="email" class="form-control" id="email" name="email" value="<?=$row->email?>" required />
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-lg-2" for="subject"><?=__('Subject')?>:</label>
                <div class="col-lg-10">
                    <input type="text" class="form-control" id="subject" name="subject" value="<?=$row->subject?>" required />
                </div>
            </div>
            <div class="form-group">
                <label for="content" class="control-label col-lg-2"><?=__('Message')?>:</label>
                <div class="col-lg-10">
                    <textarea rows="12" cols="26" id="content" class="form-control redactor" name="message" required ><?=$row->message?></textarea>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary"><?=__('Save')?></button>
            <a href="#" class="btn btn-default" data-dismiss="modal"><?=__('Close')?></a>
        </div>
    </div>
</form>