<?php
/**
 * @var \Bluz\Grid\Grid $grid
 * @var \Bluz\View\View $this
 */
?>

<script>
    require(['bluz.grid', 'contact-us/checkbox.mark']);
</script>

<div class="clearfix" data-spy="grid" data-grid="<?=$grid->getUid()?>">
    <nav class="navbar navbar-default" role="navigation">
        <div class="col-lg-6">
            <a href="<?=$grid->filter('mark_read', 'ne', 1)?>" class="btn btn-default navbar-btn mark-read-filter ajax">Unread</a>
            <a href="<?=$grid->filter('mark_read', 'eq', 1)?>" class="btn btn-default navbar-btn mark-read-filter ajax">Read</a>
        </div>
        <div class="col-lg-6">
            <form action="<?=$this->url('contact-us', 'grid')?>" class="navbar-form filter-form pull-right">
                <div class="input-group">
                    <?php echo
                    $this->partial(
                        'grid/filter-search.phtml',
                        [
                            'grid' => $grid,
                            'filters' => [
                                'name' => __('Name'),
                                'email' => __('Email'),
                                'mark_read' => __('Mark_read'),
                                'mark_answered' => __('Mark_answered'),
                            ]
                        ]
                    )
                    ?>
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit"><?=__("Search")?></button>
                    </span>
                </div>
            </form>
        </div>
    </nav>

    <?=$this->partial('grid/total.phtml', ['grid' => $grid]) ?>
    <?=$this->partial('grid/limit.phtml', ['grid' => $grid]) ?>

    <table class="table table-hover grid">
        <thead>
        <tr>
            <th><?=__('Id')?></th>
            <th><a href="<?=$grid->order('name')?:'#'?>"><?=__('Name')?></a></th>
            <th><a href="<?=$grid->order('email')?:'#'?>"><?=__('Email')?></a></th>
            <th width="130px"><?=__('Subject')?></th>
            <th><a href="<?=$grid->order('mark_read')?:'#'?>"><?=__('Mark read')?></a></th>
            <th><a href="<?=$grid->order('mark_answered')?:'#'?>"><?=__('Mark answered')?></a></th>
            <th><a href="<?=$grid->order('created')?>"><?=__('Created')?></a></th>
            <th width="100px"></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($grid->getData() as $row) : ?>
            <tr id=1 class="<?=($row['mark_read'] == 0) ? 'bold' : ''?>">
                <td><?=$row['id']?></td>
                <td><?=$this->nameLinking($row['name'], $row['email'])?></td>
                <td><a href="mailto:<?=$row['email']?>"><?=$row['email']?></a></td>
                <td>
                    <a href="<?=$this->url('contact-us', 'read', ['id' => $row['id']])?>" class="dialog subject" data-id="<?=$row['id']?>" data-ajax-method="get" data-modal-style="width:700px;">
                        <?=$row['subject']?>
                    </a>
                </td>
                <td>
                    <input data-url="<?=$this->url('contact-us', 'grid')?>" class="checkboxRead" type="checkbox" name="<?=$row['id']?>" <?=($row['mark_read'] == 1) ? 'checked' : ''?> >
                </td>
                <td>
                    <input data-url="<?=$this->url('contact-us', 'grid')?>" class="checkboxAnswered" type="checkbox" name="<?=$row['id']?>" <?=($row['mark_answered'] == 1) ? 'checked' : ''?> >
                </td>
                <td><?=$row['created']?></td>
                <td class="controls">
                    <a href="<?=$this->url('contact-us', 'reply', ['id' => $row['id']])?>" class="btn btn-primary btn-xs dialog reply" data-ajax-method="get" data-modal-style="width:700px;">
                        <i class="fa fa-share"></i>
                    </a>
                    <a href="<?=$this->url('contact-us', 'crud', ['id' => $row['id']])?>" class="btn btn-primary btn-xs dialog" data-ajax-method="get" data-modal-style="width:700px">
                        <i class="fa fa-pencil"></i>
                    </a>
                    <a href="<?=$this->url('contact-us', 'crud', ['id' => $row['id']])?>" class="confirm btn btn-xs btn-danger ajax" data-ajax-method="delete">
                        <i class="fa fa-trash-o"></i>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <?=$this->partial('grid/empty-rows.phtml', ['grid'=>$grid]) ?>
    <?=$this->partial('grid/pagination.phtml', ['grid'=>$grid]) ?>
    <?=$this->partial('grid/total.phtml', ['grid'=>$grid]) ?>

</div>
