<?php
/**
 * @var \Bluz\View\View $this
 */
?>

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h4 class="modal-title"><?=__('Message')?></h4>
</div>
<div class="modal-body">
    <dl class="dl-horizontal">
        <dt><?=__('Subject')?></dt>
        <dd><?=(!empty($row['subject'])) ? $row['subject'] : '[no subject]'?></dd>
        <br />
        <dt><?=__('Message')?></dt>
        <dd><?=$row['message']?></dd>
    </dl>
</div>
<div class="modal-footer">
    <div class="controls pull-left">
        <a href="<?=$this->url('contact-us', 'reply', ['id' => $row['id']])?>" class="btn btn-primary btn-xs dialog" data-ajax-method="get" data-modal-style="width:700px;">
            <i class="fa fa-share"></i>
        </a>
        <a href="<?=$this->url('contact-us', 'crud', ['id' => $row['id']])?>" class="confirm btn btn-xs btn-danger ajax" data-ajax-method="delete">
            <i class="fa fa-trash-o"></i>
        </a>
    </div>
    <form action="<?=$this->url('contact-us', 'grid')?>" class="ajax" method="get">
        <button type="submit" class="btn btn-default"><?=__('Close')?></button>
    </form>
</div>



