<?php
/**
 * @var \Bluz\View\View $this
 */
?>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h4 class="modal-title"><?=__('Reply')?></h4>
</div>
<div class="modal-body">
    <a href="<?=$this->url('contact-us', 'grid')?>">Back to grid</a>
    <dl class="dl-horizontal">
        <dt><?=__('Name')?></dt>
        <dd><?=$row['name']?></dd>
        <br />
        <dt><?=__('Email')?></dt>
        <dd><?=$row['email']?></dd>
        <br />
        <dt><?=__('Message')?></dt>
        <dd>[<?=$row['created']?>]</dd>
        <dd><?=$row['message']?></dd>
        <br />
        <dt><?=__('Reply')?></dt>
        <dd>
            <form class="form-horizontal ajax" method="post" action="<?=$this->url('contact-us', 'reply')?>" enctype="application/x-www-form-urlencoded">
                <input type="hidden" name="id" value="<?=$row['id']?>">
                <div class="form-group">
                    <div class="col-lg-8">
                        <textarea rows="5" cols="6" id="content" class="form-control redactor" name="message" required ></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-lg-6">
                        <button type="submit" class="btn btn-primary"><?=__('Reply')?></button>
                    </div>
                </div>
            </form>
        </dd>
    </dl>
</div>
<div class="modal-footer">
    <a href="#" class="btn btn-default" data-dismiss="modal"><?=__('Close')?></a>
</div>





